SUCCESS_WAIT = 1
FLASH_WAIT = 0.5
SHAKING_WAIT = 0.25
INACTIVE_WAIT = 1
ERROR_WAIT = 0.5

FLASH_FREQUENCY = 1500
SHAKING_FREQUENCY = 1000
INACTIVE_FREQUENCY = 500
ERROR_FREQUENCY = 250

SUCCES_MSG = "Branche détectée"
FLASH_MSG = "Flash détecté"
SHAKING_MSG = "Tremblement détecté"
INACTIVE_MSG = "Jeu non détecté"
ERROR_MSG = "Une erreur s'est produite"

SUCCESS_CONFIRMATIONS = 1
FAIL_CONFIRMATIONS = 3

BASE_COVERAGE = 0.5
WHITE_COVERAGE = 1
BROWN_MAIN_COVERAGE = 1
BROWN_SHAKE_COVERAGE = 0.1

WHITE = (255, 255, 255)
BROWN = (95, 41, 0)
